# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-17 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordid', models.CharField(max_length=50)),
                ('record_timestamp', models.CharField(max_length=50)),
                ('field_id', models.CharField(max_length=50)),
                ('field_yearcast', models.CharField(max_length=50)),
                ('field_geo_point_2d_0', models.FloatField()),
                ('field_geo_point_2d_1', models.FloatField()),
                ('field_countyid', models.IntegerField()),
                ('geoshape_type', models.CharField(max_length=50)),
                ('geoshape_coord_0', models.FloatField()),
                ('geoshape_coord_1', models.FloatField()),
                ('field_location', models.CharField(max_length=50)),
                ('marker_title', models.CharField(max_length=50)),
                ('marker_text', models.CharField(max_length=500)),
                ('main_term', models.CharField(max_length=50)),
                ('gps', models.CharField(default='N', max_length=1)),
                ('unique_key', models.CharField(max_length=50)),
                ('y_coord', models.FloatField()),
                ('sketch', models.TextField()),
                ('x_coord', models.FloatField()),
                ('object_id', models.IntegerField()),
            ],
        ),
    ]
