# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markermodel',
            name='gps',
            field=models.CharField(default='N', max_length=50),
        ),
        migrations.AlterField(
            model_name='markermodel',
            name='marker_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='markermodel',
            name='marker_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='markermodel',
            name='recordid',
            field=models.TextField(),
        ),
    ]
