# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marker_app', '0002_auto_20160918_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markermodel',
            name='field_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='markermodel',
            name='field_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='markermodel',
            name='field_yearcast',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='markermodel',
            name='geoshape_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='markermodel',
            name='gps',
            field=models.CharField(default='N', max_length=255),
        ),
        migrations.AlterField(
            model_name='markermodel',
            name='main_term',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='markermodel',
            name='record_timestamp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='markermodel',
            name='unique_key',
            field=models.CharField(max_length=255),
        ),
    ]
