# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marker_app', '0003_auto_20160918_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markermodel',
            name='x_coord',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='markermodel',
            name='y_coord',
            field=models.CharField(max_length=255),
        ),
    ]
